### ISSUE TITLE
[Crash] 1.3.5 with TOP

### ISSUE THREAD

**Issue by joklbash** [SuperMartijn642/Entangled1.12#23]
**Version Info**
MC 1.16.5
Entangled 1.3.5
TOP 3.1.4

**Steps to Reproduce**
Upgrading from Entangled 1.3.4 to 1.3.5 causes crash during load. 

**Crash report (~/logs/latest.log)**
Stacktrace:
	at mcjty.theoneprobe.TheOneProbe.lambda$processIMC$4(TheOneProbe.java:131) ~[theoneprobe:1.16-3.1.4] {re:classloading}
-- MOD theoneprobe --
Details:
	Mod File: theoneprobe-1.16-3.1.4.jar
	Failure message: The One Probe (theoneprobe) encountered an error during the process_imc event phase
		java.lang.ClassCastException: com.supermartijn642.entangled.integration.TheOneProbePlugin cannot be cast to java.util.function.Function
	Mod Version: 1.16-3.1.4
	Mod Issue URL: http://github.com/McJtyMods/TheOneProbe/issues
	Exception message: java.lang.ClassCastException: com.supermartijn642.entangled.integration.TheOneProbePlugin cannot be cast to java.util.function.Function
Stacktrace:
	at mcjty.theoneprobe.TheOneProbe.lambda$processIMC$4(TheOneProbe.java:131) ~[theoneprobe:1.16-3.1.4] {re:classloading}
	at net.minecraftforge.fml.InterModComms$QueueFilteringSpliterator.tryAdvance(InterModComms.java:171) ~[forge:?] {re:classloading}
	at java.util.Spliterator.forEachRemaining(Spliterator.java:326) ~[?:1.8.0_242] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647) ~[?:1.8.0_242] {}
	at mcjty.theoneprobe.TheOneProbe.processIMC(TheOneProbe.java:128) ~[theoneprobe:1.16-3.1.4] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[forge:36.1] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_242] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) ~[?:1.8.0_242] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_242] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_242] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_242] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_242] {}

**Comment by SuperMartijn642** [comment]
I fixed it now in version 1.3.5a for Minecraft 1.14, 1.15, and 1.16.

Thank you for reporting the issue!
